language: python
python:
  - "2.7"
  # No python 3 support yet.
  - "pypy"
# command to install dependencies
install:
  - pip install --use-mirrors cython
  - pip install --use-mirrors -r requirements.txt
# command to run tests
script: 
  - nosetests --with-coverage --cover-package=Chemistry
# lets not forget coverage
after_success: 
  - coveralls
