language: python

python:
  - "2.7"
  # No python 3 support yet.
  #- "pypy"
  # openbabel breaks pypy https://bitbucket.org/pypy/pypy/issue/1382/

before_install:
  - sudo apt-get update -qq
  - sudo apt-get build-dep -qq -y python-pygame
  - sudo apt-get install -qq -y python-pygame
  - chmod ugo+x openbabel_reqs.sh
  - "./openbabel_reqs.sh"

install:
  - sudo pip install --use-mirrors -q cython==0.20.2
  - sudo pip install --use-mirrors -q -r requirements.txt

script:
  - nosetests --with-coverage --cover-package=Chemistry

after_success:
  - coveralls
