language: python
python:
  - "2.7"
  # No python 3 support yet.
  - "pypy"
before_install:
  - sudo apt-get update -qq
  #- sudo apt-get build-dep -qq -y python-pygame
  #- sudo apt-get install -qq -y python-pygame
  - sudo apt-get install -qq -y python-openbabel
  - sudo apt-get install -qq -y openbabel
  - sudo apt-get install -qq -y swig
  - dpkg -L python-openbabel
  - dpkg -L openbabel
install:
  #- pip install --use-mirrors -q cython==0.20.2
  #- pip install --use-mirrors kivy
  - pip install --use-mirrors openbabel
  #- pip install --use-mirrors -r requirements.txt
script:
  - nosetests --with-coverage
after_success:
  - coveralls
