language: python
python:
  - "2.7"
  # No python 3 support yet.  I'm curious about pypy though...
  - "pypy"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script: 
  - nosetests --with-coverage --cover-package=Chemistry
# lets not forget coverage
after_success: 
  - coveralls
