#:kivy 1.8.0

<Workbench>:
    canvas:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            pos: self.pos
            size: self.size
            
<Output>:
    canvas:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            pos: self.pos
            size: self.size  
                
<tElement>:
    size: 10,10
    pos: self.pos
    
    BoxLayout:
        size_hint: None, None
        size: 30, 30
        canvas:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                pos: self.pos
                size: 30, 30
            
        Label:
            pos: self.pos
            text: root.text
            color: 0, 0, 0, 1
            
<tBond>:

<tCharge>:
    size: 10, 10
    pos: self.pos
    
    BoxLayout:
        size_hint: None, None
        size: 10, 10
        canvas:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                pos: self.pos
                size: 10, 10
        
        Label:
            pos: self.pos
            text: root.text
            color: 0, 0, 0, 1

<tLPE>:
    size: 10, 10
    pos: self.pos
    
    BoxLayout:
        size_hint: None, None
        size: 10, 10
        canvas:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                pos: self.pos
                size: 10, 10
        
        Label:
            pos: self.pos
            text: root.text
            color: 0, 0, 0, 1

<tRad>:
    size: 10, 10
    pos: self.pos
    
    BoxLayout:
        size_hint: None, None
        size: 10, 10
        canvas:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                pos: self.pos
                size: 10, 10
        
        Label:
            pos: self.pos
            text: root.text
            color: 0, 0, 0, 1

<RootWidget>:
    BoxLayout:                
        orientation: 'vertical'
        padding: 20
        spacing: 15
        size: root.size
        
        BoxLayout:
            orientation: 'horizontal'
            spacing: 10
            size_hint: 1, 0.15
            
            BoxLayout:
                orientation: 'vertical'
                spacing: 10
                
                BoxLayout:
                    orientation: 'horizontal'
                    spacing: 10
                    
                    Button:
                        id: element
                        text: "Element"
                        on_press: root.setType(1)
                        
                    Button:
                        id: bond
                        text: "Bond"
                        on_press: root.setType(2)
                        
                    Button:    
                        id: charge
                        text: "Charge"
                        on_press: root.setType(3)
                        
                    Button:
                        id: radical
                        text: "Radical"
                        on_press: root.setType(4)
                        
                    Button:
                        id: lone_pair
                        text: "Lone Pair"
                        on_press: root.setType(5)
                        
                BoxLayout:
                    orientation: 'horizontal'
                    spacing: 10
                    
                    Button:
                        id: add
                        text: "Add"
                        on_press: root.setMode(1)
                        
                    Button:
                        id: remove
                        text: "Remove"
                        on_press: root.setMode(2)
                        
                    Button:    
                        id: change
                        text: "Change"
                        on_press: root.setMode(3)
                        
            BoxLayout:
                orientation: 'vertical'
                spacing: 10
                size_hint: 0.3, 1
            
                Button:
                    id: publish
                    text: "Publish Molecule"
                    on_press: root.publish()
                
                Button:
                    id: reset
                    text: "Reset"
                    on_press: root.clear()
                    
    
        BoxLayout:
            orientation: 'horizontal'
            spacing: 20
            
            BoxLayout:
                orientation: 'vertical'
                spacing: 10
                
                Label:
                    id: workbench
                    text: "Workbench"
                    size_hint: 1, 0.05
                    text_size: self.width - 20, self.height
                    
                Workbench:
            
            BoxLayout:            
                orientation: 'vertical'
                spacing: 10
                size_hint: 0.35, 1

                Label:
                    id: feedback
                    text: "Feedback"
                    size_hint: 1, 0.05
                    text_size: self.width - 20, self.height
                    
                Output:               