#: kivy 1.8.0
# pyCAOS - An organic chemistry reaction simulator, written in Python
# Copyright (C) 2014 Dan Obermiller
#
# The full license is available in the root directory of the repository
#
# __author__ = "Dan Obermiller"


<ElementMode>:
    text: 'Element'
    on_press: self.callback()
    
    
<BondMode>:
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: 'vertical'
        
        Button:
            text: 'Bond'
            on_press: root.callback()
        
        BoxLayout:
            size: self.size
            pos: self.pos
            orientation: 'horizontal'
            
            Order:
            Chirality:        
    

<Order>:
    text: 'Order'
    on_press: self.callback() 
    

<Chirality>:
    text: "Chirality"
    on_press: self.callback()
    
    
<ChargeMode>:
    text: 'Charge'
    on_press: self.callback()
    
    
<ElementSelector>:
    text: 'Periodic Table'
    on_press: app.popup()


<Element>:
    size: 10, 10
    pos: self.pos
    canvas.before:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            size: root.size
            pos: root.pos
    label_: lab.__self__
    Label:
        id: lab
        pos: root.pos
        size: root.size
        text: self.text
        markup: True
        

<LabTable>:
    canvas:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            pos: root.pos
            size: self.size
            
            
<TextWindow>:
    canvas:
        Color:
            rgba: 0, .2, 1, 1
        Rectangle:
            pos: root.pos
            size: self.size
            
            
<ButtonBar>:
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: 'horizontal'
        
        ElementMode:

        ElementSelector:

        BondMode:
        
        ChargeMode:     
        
        Button:
            text: "React"
            on_press: app.react()


<Workbench>:
    size: root.size
    pos: root.pos
    orientation: 'vertical'
    
    ButtonBar:
        size_hint: 1, .1
    
    BoxLayout:
        size: self.size
        pos: self.pos
        orientation: 'horizontal'

        LabTable:    
            size_hint: .7, 1
        
        
<PeriodicTable>:
    GridLayout:
        size: root.size
        pos: root.pos
        rows: 9
        
        BoxLayout:
            Button:
                text: 'H'
                on_press: app.set_element('H')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'He'
                on_press: app.set_element('He')
                background_color: 1, 0, 0, 1
                size: 50, 80
        BoxLayout:
            Button:
                text: 'Li'
                on_press: app.set_element('Li')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Be'
                on_press: app.set_element('Be')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'B'
                on_press: app.set_element('B')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'C'
                on_press: app.set_element('C')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'N'
                on_press: app.set_element('N')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'O'
                on_press: app.set_element('O')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'F'
                on_press: app.set_element('F')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Ne'
                on_press: app.set_element('Ne')
                background_color: 1, 0, 0, 1
                size: 50, 80
        BoxLayout
            Button:
                text: 'Na'
                on_press: app.set_element('Na')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Mg'
                on_press: app.set_element('Mg')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Al'
                on_press: app.set_element('Al')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Si'
                on_press: app.set_element('Si')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'P'
                on_press: app.set_element('P')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'S'
                on_press: app.set_element('S')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Cl'
                on_press: app.set_element('Cl')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Ar'
                on_press: app.set_element('Ar')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'K'
                on_press: app.set_element('K')
                background_color: 1, 0, 0, 1
                size: 50, 80
        BoxLayout:
            Button:
                text: 'Ca'
                on_press: app.set_element('Ca')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Sc'
                on_press: app.set_element('Sc')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Ti'
                on_press: app.set_element('Ti')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'V'
                on_press: app.set_element('V')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Cr'
                on_press: app.set_element('Cr')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Mn'
                on_press: app.set_element('Mn')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Fe'
                on_press: app.set_element('Fe')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Co'
                on_press: app.set_element('Co')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Ni'
                on_press: app.set_element('Ni')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Cu'
                on_press: app.set_element('Cu')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Zn'
                on_press: app.set_element('Zn')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Ga'
                on_press: app.set_element('Ga')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Ge'
                on_press: app.set_element('Ge')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'As'
                on_press: app.set_element('As')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Se'
                on_press: app.set_element('Se')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Br'
                on_press: app.set_element('Br')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Kr'
                on_press: app.set_element('Kr')
                background_color: 1, 0, 0, 1
                size: 50, 80
        BoxLayout
            Button:
                text: 'Rb'
                on_press: app.set_element('Rb')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Sr'
                on_press: app.set_element('Sr')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Y'
                on_press: app.set_element('Y')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Zr'
                on_press: app.set_element('Zr')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Nb'
                on_press: app.set_element('Nb')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Mo'
                on_press: app.set_element('Mo')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Tc'
                on_press: app.set_element('Tc')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Ru'
                on_press: app.set_element('Ru')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Rh'
                on_press: app.set_element('Rh')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Pd'
                on_press: app.set_element('Pd')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Ag'
                on_press: app.set_element('Ag')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Cd'
                on_press: app.set_element('Cd')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'In'
                on_press: app.set_element('In')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Sn'
                on_press: app.set_element('Sn')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Sb'
                on_press: app.set_element('Sb')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Te'
                on_press: app.set_element('Te')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'I'
                on_press: app.set_element('I')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Xe'
                on_press: app.set_element('Xe')
                background_color: 1, 0, 0, 1
                size: 50, 80
        BoxLayout:
            Button:
                text: 'Cs'
                on_press: app.set_element('Cs')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Ba'
                on_press: app.set_element('Ba')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Ho'
                on_press: app.set_element('Ho')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Er'
                on_press: app.set_element('Er')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Tm'
                on_press: app.set_element('Tm')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Yb'
                on_press: app.set_element('Yb')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Lu'
                on_press: app.set_element('Lu')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Hf'
                on_press: app.set_element('Hf')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Ta'
                on_press: app.set_element('Ta')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'W'
                on_press: app.set_element('W')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Re'
                on_press: app.set_element('Re')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Os'
                on_press: app.set_element('Os')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Ir'
                on_press: app.set_element('Ir')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Pt'
                on_press: app.set_element('Pt')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Au'
                on_press: app.set_element('Au')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Hg'
                on_press: app.set_element('Hg')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Tl'
                on_press: app.set_element('Tl')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Pb'
                on_press: app.set_element('Pb')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Bi'
                on_press: app.set_element('Bi')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Po'
                on_press: app.set_element('Po')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'At'
                on_press: app.set_element('At')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Rn'
                on_press: app.set_element('Rn')
                background_color: 1, 0, 0, 1
                size: 50, 80

        BoxLayout:
            Button:
                text: 'Fr'
                on_press: app.set_element('Fr')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Ra'
                on_press: app.set_element('Ra')
                background_color: 1, 0, 0, 1
                size: 50, 80
                
            Button:
                text: 'Rf'
                on_press: app.set_element('Rf')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Db'
                on_press: app.set_element('Db')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Sg'
                on_press: app.set_element('Sg')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Bh'
                on_press: app.set_element('Bh')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Hs'
                on_press: app.set_element('Hs')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Mt'
                on_press: app.set_element('Mt')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Ds'
                on_press: app.set_element('Ds')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Rg'
                on_press: app.set_element('Rg')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Cn'
                on_press: app.set_element('Cn')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Uut'
                on_press: app.set_element('Uut')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Fl'
                on_press: app.set_element('Fl')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Uup'
                on_press: app.set_element('Uup')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Lv'
                on_press: app.set_element('Lv')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Uus'
                on_press: app.set_element('Uus')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Uuo'
                on_press: app.set_element('Uuo')
                background_color: 1, 0, 0, 1
                size: 50, 80

        BoxLayout:
            Button:
                text: 'La'
                on_press: app.set_element('La')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Ce'
                on_press: app.set_element('Ce')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Pr'
                on_press: app.set_element('Pr')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Nd'
                on_press: app.set_element('Nd')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Pm'
                on_press: app.set_element('Pm')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Sm'
                on_press: app.set_element('Sm')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Eu'
                on_press: app.set_element('Eu')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Gd'
                on_press: app.set_element('Gd')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Tb'
                on_press: app.set_element('Tb')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Dy'
                on_press: app.set_element('Dy')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
        BoxLayout:
            Button:
                text: 'Ac'
                on_press: app.set_element('Ac')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Th'
                on_press: app.set_element('Th')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Pa'
                on_press: app.set_element('Pa')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'U'
                on_press: app.set_element('U')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Np'
                on_press: app.set_element('Np')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Pu'
                on_press: app.set_element('Pu')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Am'
                on_press: app.set_element('Am')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Cm'
                on_press: app.set_element('Cm')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Bk'
                on_press: app.set_element('Bk')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Cf'
                on_press: app.set_element('Cf')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Es'
                on_press: app.set_element('Es')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Fm'
                on_press: app.set_element('Fm')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Md'
                on_press: app.set_element('Md')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'No'
                on_press: app.set_element('No')
                background_color: 1, 0, 0, 1
                size: 50, 80
    
            Button:
                text: 'Lr'
                on_press: app.set_element('Lr')
                background_color: 1, 0, 0, 1
                size: 50, 80